name: PHP Quality Assurance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Linter (PHP-CS-Fixer)
        run: composer lint

      - name: Run Static Analysis (PHPStan)
        run: composer analyse
        # ...
        # (votre job 'build' existant est juste au-dessus, ne le supprimez pas)
        # Nouveau job pour le déploiement
        deploy:
          # Condition 1: Dépendance
          # Ce job ne commencera QUE si le job 'build' a terminé avec succès.
          needs: build

          # Condition 2: Déclenchement conditionnel
          # Ce job ne s'exécutera QUE si l'événement est un push sur la branche 'main'.
          # Il sera donc ignoré pour les Pull Requests ou les pushs sur d'autres branches.
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          runs-on: ubuntu-latest

          steps:
            - name: Simuler le déploiement en production
              run: |
                echo "Déploiement sur le serveur de production..."
                echo "Connexion via SSH..."
                sleep 2
                echo "Pull du code depuis le dépôt Git..."
                sleep 2
                echo "Lancement des migrations de base de données..."
                sleep 3
                echo "Déploiement terminé avec succès !"
